"""
Routino allows developers/users to use and create vehicle profiles.
There are some default vehicle profiles but for the Dorothy project
we need specific profiles for goods transportation.

Each profile requires the following items:
  - speeds: speed limit values for road types
  - preferences: %% of preference for road type (OSM class)
  - properties: %% of preference for road property (OSM tag)
  - restrictions: vehicle attributes for road limits (height, width, etc.)

This application receives some values from the API (URL) but others are
generated here with data from official government agencies (transportation)
like the speed limits information. Road preferences are also generated by the
application in order to retrieve optimal and realistic results when using
Routino's journey planning service.
"""
